# The four fours challenge!

from math import *

print("Zero is", 4+4-4-4)
print("One is", 4/4*4/4)
print("Two is", (4*4)/(4+4))
print("Three is", factorial(4)/sqrt(4)/(sqrt(4)+sqrt(4)))
print("Four is", sqrt(4)+sqrt(4)-sqrt(4)+sqrt(4))
print("Five is", factorial(4)/4-(4/4))
print("Six is", factorial(4)/4+4-4)
print("Seven is", factorial(4)/4+(4/4))
print("Eight is", factorial(4)/4+(4/sqrt(4)))
print("Nine is", 4+4+4/4)
print("Ten is", factorial(4)/(sqrt(4))-4+sqrt(4))
print("Eleven is", (44/sqrt(4))/sqrt(4))
print("Twelve is", factorial(4)+4-4*4)
print("Thirteen is", factorial(4) - 44/4)
print("Fourteen is", 4*(4-.4)-.4)
print("Fifteen is", 4*4-4/4)
print("Sixteen is", (4**4)/(4*4))
print("Seventeen is", 4*4+4/4)
print("Eighteen is", factorial(4)+sqrt(4)-sqrt(4)*4)
print("Nineteen is", factorial(4)-4-(4/4))
print("Twenty is", factorial(4)-4+4-4)